# Generated by Django 4.2.2 on 2023-07-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_pointtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='dob',
        ),
    ]
