# Generated by Django 4.2.2 on 2023-07-15 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_coach_player_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='coach',
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.coach'),
            preserve_default=False,
        ),
    ]
