# Generated by Django 4.2.2 on 2023-07-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_player_coach_team_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
