# Generated by Django 4.2.3 on 2023-07-15 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_coach_team_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='coaches/')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
        migrations.AddField(
            model_name='team',
            name='coaches',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.coaches'),
            preserve_default=False,
        ),
    ]
