# Generated by Django 4.2.3 on 2023-07-15 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_coaches_remove_team_coach_delete_coach_team_coaches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='coaches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.coaches'),
        ),
    ]
