# Generated by Django 4.2.3 on 2023-07-15 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_team_coaches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coaches',
        ),
        migrations.DeleteModel(
            name='Coaches',
        ),
    ]
