# Generated by Django 4.2.2 on 2023-07-15 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_team_coaches'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaches',
            name='team',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.team'),
            preserve_default=False,
        ),
    ]
