# Generated by Django 4.2.2 on 2023-07-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_coaches_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='', upload_to='teams/'),
        ),
    ]
